%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\events.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\puzzles.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\teams.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\instructors.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\players.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\puzzleStates_events1.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\annotations.json"
%mongoimport%\mongoimport.exe -v --db SeriesDB_testSeriesId2 --drop --jsonArray  --file .\psdbCounters.json"