using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;

namespace PuzzleOracleV0
{
    class Administrator
    {
        static String[] tickets = {
                                      // Generated by admin-stuff.pde Processing script
                                      // on Nov 16th 2015 with seed=128
    "TKO", "BQF", "KTF", "VFB", "IRT", "WEJ", "MJQ", "JDB", "HTE", "NRE", 
    "UYA", "FPK", "PBG", "LWE", "UIQ", "LPN", "FKA", "ZHZ", "IWK", "FMX", 
    "LGO", "KWU", "WCY", "ZKV", "OHN", "WFZ", "AGA", "LVF", "CFE", "LGU", 
    "JKX", "OUL", "NDM", "BHT", "SOG", "WCF", "IKH", "RSK", "TEY", "TBP", 
    "FBZ", "TOT", "PTD", "KNJ", "THQ", "XSW", "ANC", "IXZ", "PWE", "FPO", 
    "OGT", "OYF", "ULJ", "MTA", "QAC", "UQE", "DJP", "TMS", "DPC", "RQU", 
    "BCY", "JVT", "ZLL", "BTL", "VZJ", "MAG", "RXF", "NAW", "QFH", "VGT", 
    "EEL", "BLA", "DMA", "WLC", "KRP", "PMU", "CYT", "GFS", "XKQ", "TQH", 
    "TNU", "OLZ", "VJE", "AYR", "UOC", "DQM", "NSK", "JEL", "FWP", "GDK", 
    "LFT", "FEU", "LRH", "OFC", "YSE", "SHQ", "BAG", "LIL", "BDW", "MZH"
                                  };
        static String[] activityTypeFormatStrings = {
                                            // {0} is oracle response, {1} is activity name and {2} is ticket
                                            // DISABLED - direction players to a specific challenge is DISABLED
                                            //"{0}\nCONGRATULATIONS, you have unlocked challenge \"{1}\"!"
                                            // + " Two members of your guild should present secret code \"{2}\" to the \"{1}\" challenge station."
                                            // + " Do not share this code with another clan.",
                                            //
                                            "{0}\n\nCONGRATULATIONS, you have unlocked a CHALLENGE!"
                                            + " Two members of your guild should present secret code \"{2}\" to central command for further instructions."
                                            + " Do not share this code with another clan.",
                                            "{0}\n\nCONGRATULATIONS, your guild has won ticket \"{2}\" to a QUEST!"
                                            + " Two members of your guild should present this ticket to central command for further instructions."
                                            //+ " Please give someone in your guild who has not yet gone on a quest the chance to do so."
                                            + " Do not share this ticket with another clan!"
                                        };
        static string[] challengeNames =
        {
            // We don't send people to specific challenges...
            /*
"Impromptu Skit",
"Landmarks",
"Go Naturalist",
"Voluminous",
"Win in a min",
"Portraiture",
"Builder"
             */
        };

        static string[] questNames = 
        {
            //  We don't send people to specific quests...
        };

        static string[][] activityNames = 
        {
            challengeNames,
            questNames
        };

        static int[,] activityData = {
     // PuzzleID, ActivityType, ActivityIndex, TicketIndex

     // GENERATED BY Processing script admin-stuff on November 16th, 2015.
    // Challenges ...
    // NO SKIT! {886, 0, 0, 0}, // Impromptu Skit -> TKO (Guild 1)
    {107, 0, 1, 1}, // Landmarks -> BQF (Guild 2)
    {193, 0, 1, 2}, // Landmarks -> KTF (Guild 3)
    {489, 0, 1, 3}, // Landmarks -> VFB (Guild 4)
    {319, 0, 2, 4}, // Go Botany -> IRT (Guild 5)
    {350, 0, 2, 5}, // Go Botany -> WEJ (Guild 6)
    {803, 0, 2, 6}, // Go Botany -> MJQ (Guild 1)
    {118, 0, 3, 7}, // Voluminous -> JDB (Guild 2)
    {852, 0, 3, 8}, // Voluminous -> HTE (Guild 3)
    {240, 0, 3, 9}, // Voluminous -> NRE (Guild 4)
    {884, 0, 4, 10}, // Win in a min -> UYA (Guild 5)
    {686, 0, 4, 11}, // Win in a min -> FPK (Guild 6)
    {887, 0, 4, 12}, // Win in a min -> PBG (Guild 1)
    {590, 0, 5, 13}, // Drawing -> LWE (Guild 2)
    {892, 0, 5, 14}, // Drawing -> UIQ (Guild 3)
    {650, 0, 5, 15}, // Drawing -> LPN (Guild 4)
    {609, 0, 6, 16}, // Builder -> FKA (Guild 5)
    {347, 0, 6, 17}, // Builder -> ZHZ (Guild 6)
    {881, 0, 6, 18}, // Builder -> IWK (Guild 1)

    // Quests ...
    {684, 1, 0, 19}, // Quest 1 -> FMX (Guild 1)
    {765, 1, 2, 20}, // Quest 3 -> LGO (Guild 2)
    {540, 1, 4, 21}, // Quest 5 -> KWU (Guild 3)
    {585, 1, 6, 22}, // Quest 7 -> WCY (Guild 4)
    {101, 1, 8, 23}, // Quest 9 -> ZKV (Guild 5)
    {537, 1, 10, 24}, // Quest 11 -> OHN (Guild 6)
    {203, 1, 1, 25}, // Quest 2 -> WFZ (Guild 1)
    {394, 1, 3, 26}, // Quest 4 -> AGA (Guild 2)
    {292, 1, 5, 27}, // Quest 6 -> LVF (Guild 3)
    {664, 1, 7, 28}, // Quest 8 -> CFE (Guild 4)
    {578, 1, 9, 29}, // Quest 10 -> LGU (Guild 5)
    {725, 1, 11, 30}, // Quest 12 -> JKX (Guild 6)

                                         {998, 0, 0, 0},
                                         {999, 1, 0, 1}
                                         //{333, 1, 1, 2}
                                     };

        // Build puzzle-specific extended response that gives instructions on next steps,
        // given the player's puzzle response.
        public static string buildExtendedResponse(string id, PuzzleResponse pr)
        {
            if (pr.code != PuzzleResponse.ResponseCode.Correct)
            {
                return "";
            }
            String response = "";

            int puzzleId  = Convert.ToInt32(id);
            Debug.Assert(puzzleId >= 100 && puzzleId <= 999);
            for (int i = 0; i < activityData.GetLength(0); i++)
            {
                if (activityData[i, 0] == puzzleId)
                {
                    int activityType = activityData[i, 1];
                    int activityIndex = activityData[i, 2];
                    int ticketIndex = activityData[i, 3];
                    String[] names = activityNames[activityType];
                    // Discregard activity index if there are no activity names
                    String activity = (names.Length==0)? null : names[activityIndex] ;
                    String ticket = tickets[ticketIndex];
                    string format = activityTypeFormatStrings[activityType];
                    response = String.Format(format, pr.response, activity, ticket);
                }
            }
            return response;
        }
    }
}
